blank_issues_enabled: false
contact_links:
  - name: Latest Builds / 最新构建
    url: https://github.com/mrqx0195/mrqx-s-Slashblade-Core/actions
    about: You can find the latest build JAR files at GitHub Actions.